--- 
- name: set up webserver
  hosts: host
  remote_user: ubuntu
  tasks:
    - name: ensure nginx is at the latest version
      become: yes
      become_user: root
      apt:
        name: nginx
        state: latest
    - name: start nginx
      become: yes
      become_user: root
      service: 
        name: nginx
        state: started
        enabled: yes
- name: Apply the RocketChat.Server role to all chat_servers
  hosts: chatserver
  roles:
    - RocketChat.Server